# Generated by Django 4.1.2 on 2022-11-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=10)),
                ("pw", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "admin",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AdminContent",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(blank=True, max_length=1000, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("upload_date", models.DateField(blank=True, null=True)),
                ("update_date", models.DateField(blank=True, null=True)),
                ("view_cnt", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "admin_content",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CeoOrder",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.IntegerField()),
            ],
            options={
                "db_table": "ceo_order",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("menu_cate", models.IntegerField()),
                ("food_name", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "menu",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("account", models.CharField(max_length=30)),
                ("location", models.CharField(max_length=50)),
                ("review", models.CharField(blank=True, max_length=100, null=True)),
                ("grade", models.IntegerField(blank=True, null=True)),
                ("menu_no", models.IntegerField()),
            ],
            options={
                "db_table": "store",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("id", models.CharField(max_length=50, unique=True)),
                ("pw", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("addr", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20, unique=True)),
                ("ceo", models.IntegerField(blank=True, null=True)),
                ("order_num", models.IntegerField(blank=True, null=True)),
                ("order_count", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserContent",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.CharField(blank=True, max_length=1000, null=True)),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                ("upload_date", models.DateField(blank=True, null=True)),
                ("update_date", models.DateField(blank=True, null=True)),
                ("view_cnt", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_content",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserOrder",
            fields=[
                ("no", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.IntegerField()),
                ("food_name", models.CharField(max_length=20)),
                ("store_name", models.CharField(max_length=20)),
                ("order_date", models.DateField()),
                ("number", models.IntegerField()),
                ("price", models.IntegerField()),
                ("tip", models.IntegerField(blank=True, null=True)),
                ("payment", models.CharField(max_length=20)),
                ("for_ceo", models.CharField(blank=True, max_length=100, null=True)),
                ("for_rider", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "user_order",
                "managed": False,
            },
        ),
    ]
